### ISSUE TITLE
[zabbix-community/zabbix] extraDeploy section

### ISSUE THREAD

**Issue by sinux-l5d** [zabbix-community/helm-zabbix#119]
**Is your feature request related to a problem? Please describe.**
We're deploying this chart but we need to add an Secret object "manually". In other charts, we usually use an extraDeploy key (like in bitnami charts) and a helm-secrets reference path (ref+azurekeyvault://...).

**Describe the solution you'd like**
Add an extraDeploy section for any hand-crafted extra object.

**Describe alternatives you've considered**
Use a helm-secret reference path directly in an environment variable, but that let anyone access the secret from the deployment object.

If you're okay with the [bitnami approch](https://github.com/bitnami/charts/blob/main/template/CHART_NAME/templates/extra-list.yaml), I can work on a PR.

**Comment by aeciopires** [comment]
Hello @sinux-l5d!
 
I agree with @fibbs!
 
We can support and review the PR... but I think this goes beyond the initial purpose of the helm chart. 

I understand that everyone has specific needs when deploying... but if we support everything, it will become increasingly difficult to maintain the chart.

**Comment by sinux-l5d** [comment]
Hello @fibbs, hello @aeciopires,

Yes, I mean to include arbitrary manifests in `values.yaml`. We usually stick to Bitnami charts whenever possible, to maintain coherence between all our deployments. Bitnami always includes an `extraDeploy`/`extraManifest` field for use cases they can't predict.

On our end, we're trying to streamline the deployment workflow: we use Helm to deploy a stack and Helmfile to run the Helm CLI commands. It seems like a good practice to have all objects related to a certain deployment in the same Helm release. That way, if we need to rollback, for example, we don't have to modify other manifests by hand.

I wasn't aware of the Kustomize/Helm combo. At first glance, it seems we could patch charts when needed, but the extra manifests wouldn't be included in the Helm release, right? I don't think adding `extraManifest`/`extraDeploy` would be too much work to maintain, as it essentially splits a YAML list of objects into one file, separated by `---`. 

If you think this feature suits your users' use cases, I would be happy to help 😄.

**Comment by aeciopires** [comment]
Hi @sinux-l5d!

Feel free to open the PR, adjust the documentation and values.yaml.

I suggest adding ``extraManifest``, it's clearer for those who want to add whatever else they need... Remember to add and test all occurrences of extra parameters like extraEnv, for example.

**Comment by sinux-l5d** [comment]
Just to be sure @aeciopires,

you mean adding extraManifest along with extraEnvs, extraVolumes, extraVolumesMounts ?

**Comment by fibbs** [comment]
yeah, exactlly. Should be on highest level of the values.yaml structure. I would suggest `extraManifests` though (plural), as it would be a list...
