### ISSUE TITLE
[zabbix-community/zabbix] when using nodeSelector, extraInitContainers cannot be empty

### ISSUE THREAD

**Issue by Marck** [zabbix-community/helm-zabbix#12]
**Describe the bug**
If I use nodeSelector in the values.yaml, I get an error saying the following:
```bash
Error: template: zabbix/templates/statefulset-zabbix-proxy.yaml:32:22: executing "zabbix/templates/statefulset-zabbix-proxy.yaml" at <.Values.zabbixproxy.extraInitContainers>: nil pointer evaluating interface {}.zabbixproxy
```

Looking in the code I think the extraInitContainers value cannot be empty when using nodeSelector.
For reference, I use a values.yaml that only has definition for db_access and zabbixproxy as this is what I need.

**Version of Helm and Kubernetes**:
Azure AKS, helm v3.10.2

**What happened**:
I got an error

**What you expected to happen**:
Creation of the zabbix proxy

**How to reproduce it** (as minimally and precisely as possible):
Remove all references of zabbix_server, zabbix_web, ingress, ingress_route, route and leave the following:
zabbix_agent
zabbix_proxy
db_access

**Anything else we need to know**:
Not that I think off

**Comment by aeciopires** [comment]
Hi @Marck!

Thanks for report this issue!

This was my error of CRTL+C and CRTL+V. Sorry. I fixed in this PR: https://github.com/zabbix-community/helm-zabbix/pull/10

**Comment by sa-ChristianAnton** [comment]
Version 3.4.0 released some seconds ago. @Marck please check and verify this issue is fixed.

**Comment by Marck** [comment]
I can confirm it works, thanks guys!
