### ISSUE TITLE
[zabbix-community/zabbix] Fresh installation with 6.1.1 no DB schema

### ISSUE THREAD

**Issue by remmen-io** [zabbix-community/helm-zabbix#133]
I'm struggling with version 6.1.1 to create a fresh installation of zabbix. Not sure if this is fixed with https://github.com/zabbix-community/helm-zabbix/issues/122 as it did not work for me

The zabbix-server "init-wait-for-database-schema" pod fails with

```
2024-12-03 14:04:23.380Z init-wait-for-database-schema ** DB Version not found yet, assuming DB schema is not yet created
2024-12-03 14:04:23.380Z init-wait-for-database-schema *** Waiting 5 seconds...
```

I do see the postgres server pod and can connect to it

```
zabbix@zabbix-zabbix-server-56889bb84f-kd5rl:/var/lib/zabbix$ psql -h zabbix-postgresql
Password for user zabbix:
psql (16.4 (Ubuntu 16.4-0ubuntu0.24.04.2), server 16.5 (Debian 16.5-1.pgdg120+1))
Type "help" for help.

zabbix=#
zabbix=# \dt
Did not find any relations.
zabbix=# \dn
      List of schemas
  Name  |       Owner
--------+-------------------
 public | pg_database_owner
(1 row)

zabbix=# \dt
Did not find any relations.
```

I'm using ArgoCD to deploy the helm chart with minimal configuration

```
values: |
        zabbixServerHA:
          enabled: false
```
Did I miss something?

**Comment by fibbs** [comment]
Hi! I am rather sure it's not directly related to how the Helm Chart works and how it initializes the database and the schema, as this has been tested quite extensively. Could you give me a bit more context where this part exactly comes from?

```
values: |
        zabbixServerHA:
          enabled: false
```

Is this part of your ArgoCD "application"?

My suspect is that argoCD somehow ignores that part of values which should disable native Zabbix server HA, falling back to the default which is `enabled: true` and somehow struggles with the post-install job which then would be necessary to initialize the database. I have seen similar situations of ArgoCD ignoring jobs that are marked as post-install jobs when using a Helm Chart as a Subchart to another one.

By the way, the setting to disable native server HA is `zabbixServer.zabbixServerHAenabled: false`, so in case your notation as you did is correct, it should rather be

```
values: |
  zabbixServer:
    zabbixServerHA:
      enabled: false
```

**Comment by remmen-io** [comment]
Thanks a lot, I just missed the `zabbixServer:` part. Didn't look properly! 

Now everything works
