### ISSUE TITLE
[zabbix-community/zabbix] Mysql missing

### ISSUE THREAD

**Issue by seanfariacustomink** [zabbix-community/helm-zabbix#18]
**Is your feature request related to a problem? Please describe.**
No mysql documentation, has it been dropped or just missing

**Describe the solution you'd like**
Update docs to have mysql support for example: 
https://artifacthub.io/packages/helm/fermosit/zabbix-server-mysql/0.0.5

**Comment by aeciopires** [comment]
Hi @seanfariacustomink!

Despite knowing that Zabbix officially supports MySQL and other types of databases, this helm chart has only focused on PostgreSQL since the first commits. Supporting many databases in a helm chart requires a lot of technical effort and time.

If you have the proper knowledge and time to tweak this helm chart and make it flexible to support multiple database types, starting with MySQL, we'd be happy to review and test your changes.

Merry Christmas and have an excellent 2023 for you, your family and friends.

**Comment by seanfariacustomink** [comment]
Hi @aeciopires,

Seems like a lot of this work is already done, i.e. [mysql-zabbix-helm-chart](https://github.com/dj-wasabi/helm-zabbix )

**Comment by seanfariacustomink** [comment]
Hi @aeciopires, 
Rather than support MySQL or etc databases can the instructions be provided for someone to point to an existing MySQL DB?

**Comment by aeciopires** [comment]
Hi @seanfariacustomink!

Good idea. It's a better way. Do you agree @sa-ChristianAnton?

**Comment by inggaboluna** [comment]
Support  for external dbs would be highly appreciate it.

**Comment by ralfhauser** [comment]
> Support for external dbs would be highly appreciate it.

Also for us, currently most useful would be a helm-chart variant where the persistence (mariaDB or mysql) is outside k8s - any hints for this one ?

**Comment by marijusGood** [comment]
External DBs would help our team a lot. I've seen PRs that in part address this issue already https://github.com/zabbix-community/helm-zabbix/pull/25 
We have tried to replace zabbix/zabbix-server-pgsql with a mysql one and our own DB but the server could not start. Is there some volume misconfiguration that we need to fix?

**Comment by aeciopires** [comment]
Hello @marijusGood @ralfhauser @xeberth @inggaboluna @seanfariacustomink!

I understand the importance of supporting MySQL/MariaDB and other databases supported by Zabbix.

But unfortunately I don't have the knowledge and time to implement this feature.

I made a lot of changes to the helm chart to unlock unique PostgreSQL configurations, but that's about it.

Another problem for us is running multiple tests on each database type with each new version of the chart. We do not have automated tests.

But if anyone has time to contribute, I'd appreciate it.

Have a nive week.
