### ISSUE TITLE
[zabbix-community/zabbix] Ingress path error /

### ISSUE THREAD

**Issue by mateusstamm** [zabbix-community/helm-zabbix#31]
I'm configuring a Zabbix via Kubernetes, but through NodePort, when I configure the zabbix-zabbix-web service as NodePort, I can access normally, the site follows the routes according to the change of sections, example: 

http://172.50.50.25:31508/zabbix/zabbix.php

However I have an Nginx Ingress Controller working in my cluster, and when I activate the Ingress option, first the FrontEnd is all disfigured, as if there was no CSS on the page... and when I access it and see that it would have to go to the /zabbix/zabbix.php page, but it gets lost, it sends it directly to /zabbix.php (generating a problem with the ingress, which should have the /zabbix prefix before /zabbix. php). 

How could I solve this problem? (I'm using a Local Cluster)

As I have several applications in the cluster, I would like Zabbix to be in the /zabbix route and apparently I couldn't configure it correctly, I don't know how to solve it... Maybe change the DocumentRoot, I need help.

Ingress /zabbix route
![image](https://user-images.githubusercontent.com/96153029/221697383-ecf29b1b-c2f0-463e-86f1-e01696d246b5.png)

After log in: (404 Not Found)
![image](https://user-images.githubusercontent.com/96153029/221697546-e7d52995-5a16-4498-b91b-11d8754a5860.png)

If I try /zabbix/zabbix.php
![image](https://user-images.githubusercontent.com/96153029/221697712-f35bc60e-762e-4a18-bd0f-04b06aea3236.png)

After log in: (zabbix/zabbix.php again)
![image](https://user-images.githubusercontent.com/96153029/221697864-afe2cbfd-8d9b-4264-a84d-a7829eaa3e1e.png)

**Comment by BGmot** [comment]
It's not really a problem of this helm chart.
Anyway can you please clarify how you access Zabbix WebUI without egress? It should not have /zabbix, i.e. it should be http://<url>/zabbix.php?action=dashboard.view

**Comment by mateusstamm** [comment]
> It's not really a problem of this helm chart. Anyway can you please clarify how you access Zabbix WebUI without egress? It should not have /zabbix, i.e. it should be http:///zabbix.php?action=dashboard.view

I can access by http://172.50.50.25:31508/zabbix/zabbix.php?action=dashboard.view (Nodeport) or http://172.50.50.25:8080/zabbix/zabbix.php?action=dashboard.view (LoadBalancer Service)

**Comment by BGmot** [comment]
that is weird, in my Zabbix deploy from this Helm chart serves everything from root /. What image do you use? Mine is `zabbix_image_tag: ubuntu-6.2.7`
Regardless... if you are getting everything from /zabbix path then it shouldn't be a problem to do the same with Ingress, what's your Ingress configuration?

**Comment by mateusstamm** [comment]
I'm using the same image, ubuntu-6.2.7

**ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - paths:
        - path: /zabbix
          pathType: ImplementationSpecific
  tls: []
  pathType: Prefix**

**Comment by mateusstamm** [comment]
When I log in to http://172.50.50.25:8080/ and try http://172.50.50.25/zabbix, I get redirected to http://172.30.75.3/zabbix.php?action=dashboard.view, without /zabbix path before. I think I need change the Root path into Zabbix config.. from / to /zabbix, but where?

**Comment by BGmot** [comment]
I think when you go to  http://172.50.50.25/zabbix then ingress rewrites it to / and what nginx server sees is  http://172.50.50.25/ and Zabbix WebUI code redirects to /index.php (or if you are logged in then to /zabbix.php?action=dashboard.view) which is effectively http://172.50.50.25/index.php.
I am afraid you need to build your own zabbix-web-nginx-pgsql image so nginx serves with /zabbix path not with / (or mount appropriate nginx config.
Wouldn't be easier for you to create a DNS record for zabbix and route to Zabbix Web Service based on hostname (without any re-writes)?
This is how I do it in variables for ingress:
```
ingress:
  enabled: true
  hosts:
    - host: x-mblab.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: mblab-tls
      hosts:
        - x-mblab.local
  ingressClassName: nginx
  pathType: Prefix
```
