### ISSUE TITLE
CronJobs

### ISSUE THREAD

**Issue by dpsw6914** [zabbix-community/helm-zabbix#38]
When running CronJobs it was not cleaning any old stopped cluster in zabbix ui. Am i missing something? or it was known bug?

**Comment by sravanre** [comment]
For my cluster the old zabbix server pods are being cleaned up in the Zabbix UI

**Comment by dpsw6914** [comment]
> For my cluster the old zabbix server pods are being cleaned up in the Zabbix UI

mine wasn't. and after restarting the ubuntu hosting kubernetes i ecounter zabbbix server not running because "Containers with incomplete status: [init-wait-for-database-schema]"

**Comment by fibbs** [comment]
I have been inactive here for a while. This was very surely a problem with database not being available or something similar. Is this still an actively existing problem or can we close this issue?

**Comment by aeciopires** [comment]
I will close the issue, but if the problem persists, another issue can be opened.
