### ISSUE TITLE
[zabbix-community/zabbix] Missing query if zabbixserver is enabled

### ISSUE THREAD

**Issue by tiroso** [zabbix-community/helm-zabbix#4]
**Describe the bug**
Missing query if zabbixserver is enabled. I have a lot customer systems with zabbix proxy deployed. In your template "job-init-db-schema.yaml" is only a query if zabbixserver replica count greater than 1. As a workaround set the the replica count to 1 or zero...but it would be nicer to have a query if zabbixserver is also enabled

![image](https://user-images.githubusercontent.com/22832456/192484318-e0021df2-7a9b-4712-9c61-46ee452d1404.png)

**Comment by sa-ChristianAnton** [comment]
Indeed, thanks for pointing out. Feel free to submit a PR if you have it fixed on your side already, otherwise I will fix this within the next days.

**Comment by aeciopires** [comment]
Hi guys!

This problems is fixed in this pull request: https://github.com/zabbix-community/helm-zabbix/pull/7
