### ISSUE TITLE
[zabbix-community/zabbix] Insttaling in Vmware Tanzu...

### ISSUE THREAD

**Issue by alfista-sk** [zabbix-community/helm-zabbix#40]
Hi,

please is possible to do the installation package so, that is also possible to install it directly in Vmware Tanzu?
While dont isnt the possibility to install the repository, only to build it directly from build in JAML file.

Thanks.

**Comment by aeciopires** [comment]
Hi @alfista-sk!

I don't use the VMWare Tanzu. 
I don't understand you need. Could explain better?

**Comment by alfista-sk** [comment]
Hi,
Tanzu is an Kubernetes implementation in VMware vShpere.
Its a standard Kubernetes grid, only what is others is the access to it, while its not on standard HW but in virtualization (fully integrated in Vmware vSphere for managing) and therefor there is needed to have direct access to Helm and to all configurations JAML files, while I doesn't have the possibility to install somewhere needed repository, what is needed by your actual implementation.

**Comment by aeciopires** [comment]
Hi @alfista-sk!

Sorry by late.
Thanks for the explanation.
I don't have access to a VmWare Tanzu to lear how to use. I can't help with this installation mode and creating JAML files. 
But you just need the package to try yourself, you can download it using these commands:

```
export ZABBIX_CHART_VERSION='4.0.0'

wget "https://github.com/zabbix-community/helm-zabbix/releases/download/zabbix-${ZABBIX_CHART_VERSION}/zabbix-${ZABBIX_CHART_VERSION}.tgz"

tar xzvf "zabbix-${ZABBIX_CHART_VERSION}.tgz"

cd zabbix
```

**Comment by aeciopires** [comment]
Closing this issue because I don't know how to solve. But I will appreciate if you or other person open a pull request with the solution.
