### ISSUE TITLE
duplicate imagePullSecrets warning

### ISSUE THREAD

**Issue by pirateunclejack** [zabbix-community/helm-zabbix#44]
When install zabbix with helm command
`helm install zabbix -n zabbix .` 
A warning printed out: 
```
warnings.go:70] spec.template.spec.imagePullSecrets[1].name: duplicate name ...
```
https://github.com/zabbix-community/helm-zabbix/blob/5f94e86ddefd12c74e619072c153b2f6292568c9/charts/zabbix/templates/statefulset-postgresql.yaml#L130C1-L136C17
Should this code be? : 
```
      imagePullSecrets:
      {{- range .Values.zabbixserver.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- range .Values.postgresql.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
```

**Comment by aeciopires** [comment]
Hi @pirateunclejack!

Sorry by late.
Thanks for your report. I fix the problem in the PR https://github.com/zabbix-community/helm-zabbix/pull/46
