### ISSUE TITLE
[zabbix-community/zabbix] zabbix_server extraEnv not getting applied

### ISSUE THREAD

**Issue by batulziiy** [zabbix-community/helm-zabbix#48]
**Describe the bug**
I have zabbix helm deployment automated through FluxCD. Recently, found that the Zabbix server was unable to fetch metrics from ESXi VMware Hypervisors due to "StartVMwareCollectors" parameter set to 0 by default. So I read the instruction on github and set ZBX_STARTVMWARECOLLECTORS extraEnv as below : 
```
extraEnv:
    - name: "ZBX_STARTVMWARECOLLECTORS"
      value: "10"
```
Also tried this : 
```
ZBX_STARTVMWARECOLLECTORS: 5
```
But the change is not being applied to the zabbix_server.conf file. Any help would be appreciated. 

**Version of Helm and Kubernetes**:
helm3 and k3s 1.26

**What happened**:
Added "STARTVMWARECOLLECTORS" extraEnv to zabbix_server.

**What you expected to happen**:
Expected to have the change applied to zabbix_server.conf

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by aeciopires** [comment]
Hello @batulziiy!

Sorry for the delay in my response. Do you still have this problem?

I need more information about your helm values ​​(please hide sensitive settings like password/username etc).

In my environment this configuration works... pay attention to the indentation. YAML is very sensitive to indentation.

My example:

```bash
zabbixServer:
  enabled: true
#
#.... (hid other parameters)
# 
  extraEnv: 
    - name: ZBX_STARTVMWARECOLLECTORS
      value: "10"
```
