### ISSUE TITLE
[zabbix-community/zabbix] Adding extra params in cronjob-hanodes-autoclean

### ISSUE THREAD

**Issue by david-moreau** [zabbix-community/helm-zabbix#5]
Hi,

Thanks for your work on this helm chart.

Currently, The cronjob cann't be extra configured with the extra params of zabbix server (extraContainers, extraVolumes, extraPodSpecs,... ).

For information : we had opened an issue on the cetic repo for adding this extra params : https://github.com/cetic/helm-zabbix/pull/67/files# 

Would you be able to add the extra parameters and allow the use of cronjob-hanodes-autoclean in the exotics configurations

David

**Comment by aeciopires** [comment]
Hi guys!

This feature was added in this pull request: https://github.com/zabbix-community/helm-zabbix/pull/7
