### ISSUE TITLE
[zabbix-community/zabbix] UPGRADE FAILED

### ISSUE THREAD

**Issue by nataliagranato** [zabbix-community/helm-zabbix#55]
Fui realizar o upgrade do chart e estou com o seguinte erro: Error: UPGRADE FAILED: failed to create resource: StatefulSet in version "v1" cannot be handled as a StatefulSet: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

**Comment by aeciopires** [comment]
[Answer in PT-BR]

Olá @nataliagranato!

Poderia dar mais detalhes sobre que o que tentou fazer?

- Qual a versão do helm chart que usava antes?
- Qual a versão do helm chart que deseja atualizar?
- Qual a versão do cluster Kubernetes que está usando?
- Quais as versões dos comandos ``kubectl`` e ``helm``?

Mesmo sem saber esses detalhes, pesquisei um pouco sobre a mensagem de erro e achei alguns links... talvez as respostas possam te ajudar a identificar a causa raíz...

- https://community.dremio.com/t/helm-installation-failed-what-is-wrong-with-my-statefulset-in-version-v1-cannot-be-handled-as-a-statefulset-quantities-must-match-the-regular-expression/10018
- https://github.com/codecentric/helm-charts/issues/287
- https://github.com/kubernetes/kubernetes/issues/26898
- https://discuss.elastic.co/t/heartbeat-error-error-when-creating-heartbeat-kubernetes-yaml-deployment-in-version-v1-cannot-be-handled-as-a-deployment-unable-to-parse-quantitys-suffix-when-deploying-on-kubernetes/314597/3

Pelo o que entendi dos erros reportados em outros helm charts, parece ser algo relacionado a alguma informação no helm values que não está correta (tipo tamanho do disco, memória)... e não atende a expressão regular: ^([+-]?[0-9.]+)([eEinumkKMGTP][-+]?[0-9])$'

**Comment by nataliagranato** [comment]
Olá @aeciopires, minha versão do Kubernetes é a v1.26.7, tive que fazer uma pequena mudança no template do postgres porque ele não estava aceitando a persistência de dados:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
metadata: 
  name: {{ template "zabbix.fullname" . }}-postgresql
  labels:
    app: {{ template "zabbix.fullname" . }}-postgresql
```
Com isso consegui resolver o problema.

**Comment by aeciopires** [comment]
Oi, @nataliagranato!

Muito obrigado por compartilhar essa solução. Vou adicionar no helm chart e publicar na próxima versão.

**Comment by aeciopires** [comment]
Oi, @nataliagranato!
Olhei o código do arquivo https://github.com/zabbix-community/helm-zabbix/blob/master/charts/zabbix/templates/statefulset-postgresql.yaml e nas linhas 5 a 8 já está semelhantes ao que você falou que resolveu...

Fiquei na dúvida se a resolução é somente isso mesmo e se ainda se faz necessário.

Poderia confirmar essa informação pra mim?

**Comment by aeciopires** [comment]
Oi, @nataliagranato!

Como já faz bastante tempo e não recebi uma resposta sua, vou fechar essa issue. Se o problema voltar a ocorrer com novas versões do helm chart e do Zabbix, é só abrir outra issue com mais detalhes do problema.

PS.: Eu estava no DevOpsDays-SP e assisti a sua palestra. Muito boa e muito bom conhecer a sua jornada e evolução na área de T.I. Até o próximo evento.
