### ISSUE TITLE
[zabbix-community/zabbix] Add option to use custom service account

### ISSUE THREAD

**Issue by syphernl** [zabbix-community/helm-zabbix#70]
**Is your feature request related to a problem? Please describe.**
We're trying to setup this chart on an AKS cluster using the secrets-store CSI. For this we need to be able to add labels to a SA. 
This chart doesn't have that functionality so we tried to create our own SA, but we cannot specify this in the chart values.

**Describe the solution you'd like**
A way to provide a custom SA

**Describe alternatives you've considered**
We need to add labels to the SA. This could also be implemented instead of a custom SA, although it probably would be useful to have both.

**Additional context**
-

**Comment by aeciopires** [comment]
Hi @syphernl!
Thanks for your colaboration.
I understood your necessity. 
I will implement this feature until next week.
