### ISSUE TITLE
[zabbix-community/zabbix] Add support for custom labels

### ISSUE THREAD

**Issue by syphernl** [zabbix-community/helm-zabbix#71]
**Is your feature request related to a problem? Please describe.**

We're trying to setup this chart on an AKS cluster using the secrets-store CSI. Besides [needing a label on the SA](https://github.com/zabbix-community/helm-zabbix/issues/70) we also need a label on the pod to be able to use this driver.
It would be nice if we could add custom labels to stuff like pod, sa, services etc.

**Is your feature request related to a problem? Please describe.**

See above

**Describe the solution you'd like**

[Cert-manager](https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml) for example has `podLabels` and `serviceAccount.labels` which gets applied to the SA and Pods it creates. 
There is also a `commonLabels` option.

It would be nice to have something like that here as well, but perhaps (also) a way to specify this for specific resources (e.g. only `zabbix-server` pod)

**Describe alternatives you've considered**
-

**Additional context**
Related issue: #70

**Comment by aeciopires** [comment]
Hi @syphernl!
Thanks for your colaboration.
I understood your necessity. 
I will implement this feature until next week.
