### ISSUE TITLE
4.2.x: helm.sh/chart label duplicated on ServiceAccount

### ISSUE THREAD

**Issue by mlow** [zabbix-community/helm-zabbix#79]
**Version of Helm and Kubernetes**
Kubernetes 1.28.7
Helm v3.13.3 (via FluxCD 2.2.3/helm-controller 0.37.4)

**What happened**:
Chart fails to install

**How to reproduce it**
Attempt to apply chart version 4.2.x using FluxCD 2.2.3

**Describe the bug**
The following error occurs as a result of the `helm.sh/chart` label being specified twice in `templates/serviceaccount.yaml` - first in that template and then again in the `zabbix.labels` include:

```
 yaml: unmarshal errors:                                                                                                                                                                                     
   line 11: mapping key "helm.sh/chart" already defined at line 9
```

**Comment by ny-bbo** [comment]
I was facing the same issues. Helm will ignore those dublicate keys on `.metadata.labels` but kustomize's helm renderer wont. 
There is also another duplicate key on `templates/services.yaml` when choosing zabbixAgent to run as sidecar and deploy both server and proxy: `.spec.selector` will template out with duplicate key `app` as label selector, for both server and proxy.

Sidenote: there is yet another probem when deploying with argoCD at least: the `init-db` job goes `missing` on argoCD sfter being completed and it is not possible to add an annotation to this job, which would allow me to let this be a `pre-sync-hook`. This results on a constantly errored argo app.

**Comment by aeciopires** [comment]
Hello @mlow and @ny-bbo!

Thanks for report theese bugs... I fixed all in this PR: https://github.com/zabbix-community/helm-zabbix/pull/82 

Please install helm chart version 4.3.0
