### ISSUE TITLE
Permission issue when enabling persistance

### ISSUE THREAD

**Issue by SalmanIsha** [zabbix-community/helm-zabbix#8]
Hello,

I have almost done the bare metal installation of this helm chart except enabling the existing pv claim. And then it breaks my deployment. The postgres pod is getting error like below, I have also disabled the password auto generator:

chown: changing ownership of '/var/lib/postgresql/data/pgdata': Operation not permitted

I am very much confused where I am doing the mistakes. If I add securityContext ( runasuser: 65534) in the values.yaml file the postgres pod works fine but then the zabbix web can't up the nginx service.

Anyone have idea what is going wrong here?

**Comment by sa-ChristianAnton** [comment]
Hi there,

I do not really have an idea what is going wrong there, as I don't have this problem in any of the deployments I did so far.

What kind of storage backend are you using in your cluster? What Kubernetes Distribution are you using?

Thanks

Christian

**Comment by sa-ChristianAnton** [comment]
Want to share any details? Otherwise I would like to close this issue.

**Comment by SalmanIsha** [comment]
Hi Christian,

Sorry for not getting back to you. Our issue was solved. We had to add a security context in the values.yaml file to get it work. Our storage class was external nfs server.

Kind Regards
Mohd Salman Isha
________________________________

**Comment by sa-ChristianAnton** [comment]
I see, that's a common case then and not really specific to this helm chart. Nice to know you were able to solve it. Happy helming and happy Zabbixing :-)
