### ISSUE TITLE
[zabbix-community/zabbix] issue title

### ISSUE THREAD

**Issue by abwelt** [zabbix-community/helm-zabbix#81]
**Describe the bug**
It seems that ClusterRoleBinding and ClusterRole permissions are not part of the chart. I am not sure if this is by design but this causes an issue when trying to monitor the cluster with Zabbix as the service account that the chart creates does not have the relevant permissions to hit the api endpoints it needs to function. Not sure if this is by design or not.

**Version of Helm and Kubernetes**:
Helm: 3.14.0 Kube 1.27

**What happened**:
403 errors in zabbix trying to query kube API for node metrics

**What you expected to happen**:
Successful Auth

**How to reproduce it** (as minimally and precisely as possible):
Install the chart fresh and try and add the node http monitoring as per https://blog.zabbix.com/monitoring-kubernetes-with-zabbix/25055/

**Comment by aeciopires** [comment]
Hello @abwelt!

Thanks for report this necessity... I created the clusterrole and clusterrole-binding in this PR: https://github.com/zabbix-community/helm-zabbix/pull/82 

Please install helm chart version 4.3.0
