### ISSUE TITLE
[zabbix-community/zabbix] Make Zabbix HA great again! 

### ISSUE THREAD

**Issue by thomas-korrison** [zabbix-community/helm-zabbix#86]
Hi all, I have been looking to deploy Zabbix in HA mode with this helm chart but have been unsuccessful. Although multiple pods do get deployed in active/standby mode respectively, the web server is unable to detect the active pod, so the ui complains about the server not being available.

I have managed to get it all to work by deploying the Zabbix server as a StatefulSet and using a headless service for service discovery. As I understand it, when you use a headless service with a StatefulSet, each pod gets a unique DNS subdomain, which resolves directly to the pod’s IP address.

This DNS is typically structured as **[podname].[headless-service-name].[namespace].svc.cluster.local.**

See this issue for more details.
 zabbix/zabbix-docker/issues/931

**Describe the solution you'd like**
Enable HA mode by 
1. deploying the Zabbix server as a stateful set
2. Add a headless service for service discovery
3. modify environmental variables as appropriate

**Describe alternatives you've considered**
1. adding a leader election sidecar (sounds hacky)

**Comment by aeciopires** [comment]
Hi @thomas-korrison!
 
Unfortunately I don't have the knowledge to implement this, but if you do, I would really like to see a Pull Request about this and incorporate it into the helm chart.

I linked this issue to @sa-ChristianAnton, but I don't know if he will have the free time to implement it.

**Comment by thomas-korrison** [comment]
Thanks for the reply @aeciopires !

Yes, I think I can make a pull request with the relevant changes. Just wanted to gauge interest first before implementing anything.

**Comment by aeciopires** [comment]
Excellent @thomas-korrison!

I will really enjoy evaluating and testing your Pull Request. I wish you great research and implementation work.

In the next few days I should release another version of the helm chart containing changes from a Pull Request that was opened today and a small refactory that I think is necessary in the services objects and extraEnv config. It's good to keep an eye on synchronizing code and avoiding conflicts.

**Comment by aeciopires** [comment]
In time, Zabbix 7.0 is in release candidate. I think the final version should be out in a few weeks.

Looking at the release notes, I saw that Zabbix 7.0 has a feature related to this and I saw that we will need to change a lot in the helm chart to support the new version, as well as a new PostgreSQL, TimeScaleDB, etc... It might be interesting to wait for these releases to avoid rework... What do you think?

References:

- https://www.zabbix.com/roadmap
- https://www.zabbix.com/rn/rn7.0.0rc1
- https://www.zabbix.com/documentation/devel/en/manual/installation/requirements
- https://www.zabbix.com/documentation/devel/en/manual/installation/containers
- https://www.zabbix.com/documentation/devel/en/manual/installation/upgrade_notes_700

**Comment by thomas-korrison** [comment]
ok, that is probably a wise choice.

**Comment by aeciopires** [comment]
Hello @thomas-korrison!

I published the new version of helm chart (5.0.0) to add support Zabbix 7.0.0.
More details: https://github.com/zabbix-community/helm-zabbix/pull/96

Now you can begin the tests and work to implement this feature if necessary.

Have a nice week!

**Comment by Nyralei** [comment]
+1 for running zabbix-server as statefulset

**Comment by thomas-korrison** [comment]
I just did a deployment from the latest helm chart on minikube and it appears the HA mode works without any updates needed! If someone else can confirm this, we can probably close this issue.

**Comment by zohairraza** [comment]
Hi @thomas-korrison 

how did you manage the HA for proxies/agents?

https://www.zabbix.com/documentation/current/en/manual/concepts/server/ha 

I think we need to define 2 (or more) servers in proxies to achieve HA in Zabbix, and for that we need stateful sets.
